name: CD
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR with PAT
      env:
        PAT: ${{ secrets.GHCR_PAT }}
      run: echo "$PAT" | docker login ghcr.io -u student161002 --password-stdin
    
    - name: Build and push with PAT
      run: |
        IMAGE=ghcr.io/student161002/python-app:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" |
           docker login ghcr.io -u student161002 --password-stdin

    - name: Build and push
      run: |
        IMAGE=ghcr.io/student161002/python-app:latest
        docker build -t $IMAGE .
        docker push $IMAGE
